filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
let mapleader=","
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"

"" powerline
let g:Powerline_symbols = 'unicode'
set nocompatible   " Disable vi-compatibility
set laststatus=2   " Always show the statusline
set encoding=utf-8 " Necessary to show Unicode glyphs

"" solarized
syntax enable
if has('gui_running')
    set background=dark
    colorscheme solarized
endif
let g:solarized_hitrail = 1
let g:solarized_visibility = "high"

"" ctrlp
" <Ctrl>p - start searching
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc     " MacOSX/Linux
"set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }
let g:ctrlp_extensions = ['tag', 'buffertag', 'mixed']
nmap <A-P> :CtrlPTag<CR>
nmap <A-p> :CtrlPBufTag<CR>

"" python-mode
" <Ctrl>c rr    - rename
" <Ctrl><Space> - autocomplete
" <Leader>r     - run python file
let g:pymode_folding = 0

"" anticipate mistakes
set history=700
set undolevels=700

"" tabs not spaces
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab

"" 80 char, show tabs, trailing chars and extenders
set cc=80
set list listchars=tab:»·,trail:·,extends:¶

"" Make search case insensitive
set hlsearch
set incsearch
set ignorecase
set smartcase

"" Disable backup and swap files - they leave a mess
set nobackup
set nowritebackup
set noswapfile

"" Tagbar
nmap <Leader>t :TagbarToggle<CR>

"" unimpaired
" [<Space> - insert space above line
" <Space>] - insert space above line
" [e       - exchange with line above
" ]e       - exchange with line below

"" tcomment
" https://github.com/tomtom/tcomment_vim
" gcc - comment current line
" visual mode selection + gc - toggle comments for the tcurrent selection

"" ultisnips
" https://github.com/SirVer/ultisnips
" #!<tab> - insert python shebang and encoding
" class<tab> - insert class with docstring
" def<tab> - insert method with docstring
" <ctrl>j - move to next field
" <ctrl>k - move to previous field
