filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
let mapleader=","
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
" let g:syntastic_python_checkers=['flake8']
let g:syntastic_check_on_open=1

" powerline
let g:Powerline_symbols = 'unicode'
set nocompatible   " Disable vi-compatibility
set laststatus=2   " Always show the statusline
set encoding=utf-8 " Necessary to show Unicode glyphs

" solarized
syntax enable
if has('gui_running')
    set background=light
    colorscheme solarized
endif
